/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import yaml.helper.dsl.yamlGenDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class YamlGenDslFactoryImpl extends EFactoryImpl implements YamlGenDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static YamlGenDslFactory init()
  {
    try
    {
      YamlGenDslFactory theYamlGenDslFactory = (YamlGenDslFactory)EPackage.Registry.INSTANCE.getEFactory(YamlGenDslPackage.eNS_URI);
      if (theYamlGenDslFactory != null)
      {
        return theYamlGenDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new YamlGenDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public YamlGenDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case YamlGenDslPackage.SOURCE: return createSource();
      case YamlGenDslPackage.SOURCE_ELEMENT: return createSourceElement();
      case YamlGenDslPackage.IMPORT: return createImport();
      case YamlGenDslPackage.FIELD: return createField();
      case YamlGenDslPackage.BODY: return createBody();
      case YamlGenDslPackage.BODY_ELEMENT: return createBodyElement();
      case YamlGenDslPackage.EXTEND: return createExtend();
      case YamlGenDslPackage.NESTED_FIELD: return createNestedField();
      case YamlGenDslPackage.NESTED_FIELDS: return createNestedFields();
      case YamlGenDslPackage.PROPERTY: return createProperty();
      case YamlGenDslPackage.NAME: return createName();
      case YamlGenDslPackage.DEFAULT: return createDefault();
      case YamlGenDslPackage.HINT: return createHint();
      case YamlGenDslPackage.PERMITTED_VALUES: return createPermittedValues();
      case YamlGenDslPackage.VALUES: return createValues();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Source createSource()
  {
    SourceImpl source = new SourceImpl();
    return source;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SourceElement createSourceElement()
  {
    SourceElementImpl sourceElement = new SourceElementImpl();
    return sourceElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Field createField()
  {
    FieldImpl field = new FieldImpl();
    return field;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Body createBody()
  {
    BodyImpl body = new BodyImpl();
    return body;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BodyElement createBodyElement()
  {
    BodyElementImpl bodyElement = new BodyElementImpl();
    return bodyElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Extend createExtend()
  {
    ExtendImpl extend = new ExtendImpl();
    return extend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NestedField createNestedField()
  {
    NestedFieldImpl nestedField = new NestedFieldImpl();
    return nestedField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NestedFields createNestedFields()
  {
    NestedFieldsImpl nestedFields = new NestedFieldsImpl();
    return nestedFields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Property createProperty()
  {
    PropertyImpl property = new PropertyImpl();
    return property;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Name createName()
  {
    NameImpl name = new NameImpl();
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Default createDefault()
  {
    DefaultImpl default_ = new DefaultImpl();
    return default_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Hint createHint()
  {
    HintImpl hint = new HintImpl();
    return hint;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PermittedValues createPermittedValues()
  {
    PermittedValuesImpl permittedValues = new PermittedValuesImpl();
    return permittedValues;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Values createValues()
  {
    ValuesImpl values = new ValuesImpl();
    return values;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public YamlGenDslPackage getYamlGenDslPackage()
  {
    return (YamlGenDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static YamlGenDslPackage getPackage()
  {
    return YamlGenDslPackage.eINSTANCE;
  }

} //YamlGenDslFactoryImpl
