/*
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import yaml.helper.dsl.services.YamlGenDslGrammarAccess;
import yaml.helper.dsl.yamlGenDsl.Body;
import yaml.helper.dsl.yamlGenDsl.Default;
import yaml.helper.dsl.yamlGenDsl.Field;
import yaml.helper.dsl.yamlGenDsl.Hint;
import yaml.helper.dsl.yamlGenDsl.Import;
import yaml.helper.dsl.yamlGenDsl.Name;
import yaml.helper.dsl.yamlGenDsl.NestedField;
import yaml.helper.dsl.yamlGenDsl.NestedFields;
import yaml.helper.dsl.yamlGenDsl.PermittedValues;
import yaml.helper.dsl.yamlGenDsl.Source;
import yaml.helper.dsl.yamlGenDsl.Values;
import yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage;

@SuppressWarnings("all")
public class YamlGenDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private YamlGenDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == YamlGenDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case YamlGenDslPackage.BODY:
				sequence_Body(context, (Body) semanticObject); 
				return; 
			case YamlGenDslPackage.DEFAULT:
				sequence_Default(context, (Default) semanticObject); 
				return; 
			case YamlGenDslPackage.FIELD:
				sequence_Field(context, (Field) semanticObject); 
				return; 
			case YamlGenDslPackage.HINT:
				sequence_Hint(context, (Hint) semanticObject); 
				return; 
			case YamlGenDslPackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case YamlGenDslPackage.NAME:
				sequence_Name(context, (Name) semanticObject); 
				return; 
			case YamlGenDslPackage.NESTED_FIELD:
				sequence_NestedField(context, (NestedField) semanticObject); 
				return; 
			case YamlGenDslPackage.NESTED_FIELDS:
				sequence_NestedFields(context, (NestedFields) semanticObject); 
				return; 
			case YamlGenDslPackage.PERMITTED_VALUES:
				sequence_PermittedValues(context, (PermittedValues) semanticObject); 
				return; 
			case YamlGenDslPackage.SOURCE:
				sequence_Source(context, (Source) semanticObject); 
				return; 
			case YamlGenDslPackage.VALUES:
				sequence_Values(context, (Values) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Body returns Body
	 *     BodyElement returns Body
	 *     Extend returns Body
	 *
	 * Constraint:
	 *     elements+=BodyElement*
	 */
	protected void sequence_Body(ISerializationContext context, Body semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     BodyElement returns Default
	 *     Property returns Default
	 *     Default returns Default
	 *
	 * Constraint:
	 *     value=Values
	 */
	protected void sequence_Default(ISerializationContext context, Default semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlGenDslPackage.Literals.DEFAULT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlGenDslPackage.Literals.DEFAULT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDefaultAccess().getValueValuesParserRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SourceElement returns Field
	 *     Field returns Field
	 *
	 * Constraint:
	 *     (help+=SL_COMMENT* root?='root'? name=ID superField=[Field|ID]? body=Body)
	 */
	protected void sequence_Field(ISerializationContext context, Field semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     BodyElement returns Hint
	 *     Property returns Hint
	 *     Hint returns Hint
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_Hint(ISerializationContext context, Hint semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlGenDslPackage.Literals.HINT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlGenDslPackage.Literals.HINT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHintAccess().getValueSTRINGTerminalRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SourceElement returns Import
	 *     Import returns Import
	 *
	 * Constraint:
	 *     path=STRING
	 */
	protected void sequence_Import(ISerializationContext context, Import semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlGenDslPackage.Literals.IMPORT__PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlGenDslPackage.Literals.IMPORT__PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImportAccess().getPathSTRINGTerminalRuleCall_1_0(), semanticObject.getPath());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     BodyElement returns Name
	 *     Property returns Name
	 *     Name returns Name
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_Name(ISerializationContext context, Name semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlGenDslPackage.Literals.NAME__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlGenDslPackage.Literals.NAME__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNameAccess().getValueSTRINGTerminalRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     BodyElement returns NestedField
	 *     NestedField returns NestedField
	 *
	 * Constraint:
	 *     (help+=SL_COMMENT* mandatory?='mandatory'? field=[Field|ID]? body=Body)
	 */
	protected void sequence_NestedField(ISerializationContext context, NestedField semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     BodyElement returns NestedFields
	 *     NestedFields returns NestedFields
	 *
	 * Constraint:
	 *     (help+=SL_COMMENT* mandatory?='mandatory'? field=[Field|ID]? body=Body)
	 */
	protected void sequence_NestedFields(ISerializationContext context, NestedFields semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     BodyElement returns PermittedValues
	 *     Property returns PermittedValues
	 *     PermittedValues returns PermittedValues
	 *
	 * Constraint:
	 *     value=Values
	 */
	protected void sequence_PermittedValues(ISerializationContext context, PermittedValues semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlGenDslPackage.Literals.PERMITTED_VALUES__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlGenDslPackage.Literals.PERMITTED_VALUES__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPermittedValuesAccess().getValueValuesParserRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Source returns Source
	 *
	 * Constraint:
	 *     entries+=SourceElement+
	 */
	protected void sequence_Source(ISerializationContext context, Source semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Values returns Values
	 *
	 * Constraint:
	 *     (values+=STRING+ | values+=STRING)
	 */
	protected void sequence_Values(ISerializationContext context, Values semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
