/*
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractYamlGenDslScopeProvider extends DelegatingScopeProvider {
}
