/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl.impl;

import org.eclipse.emf.ecore.EClass;

import yaml.helper.dsl.yamlGenDsl.AnyNestedField;
import yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Any Nested Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AnyNestedFieldImpl extends AnyFieldImpl implements AnyNestedField
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnyNestedFieldImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return YamlGenDslPackage.Literals.ANY_NESTED_FIELD;
  }

} //AnyNestedFieldImpl
