/*
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class YamlGenDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("yaml/helper/dsl/parser/antlr/internal/InternalYamlGenDsl.tokens");
	}
}
