/*
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import yaml.helper.dsl.parser.antlr.internal.InternalYamlGenDslParser;
import yaml.helper.dsl.services.YamlGenDslGrammarAccess;

public class YamlGenDslParser extends AbstractAntlrParser {

	@Inject
	private YamlGenDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalYamlGenDslParser createParser(XtextTokenStream stream) {
		return new InternalYamlGenDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Source";
	}

	public YamlGenDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(YamlGenDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
