/*
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import yaml.helper.dsl.YamlGenDslRuntimeModule;
import yaml.helper.dsl.YamlGenDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class YamlGenDslIdeSetup extends YamlGenDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new YamlGenDslRuntimeModule(), new YamlGenDslIdeModule()));
	}
	
}
