/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Any Nested Field</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getAnyNestedField()
 * @model
 * @generated
 */
public interface AnyNestedField extends AnyField, BodyElement
{
} // AnyNestedField
