/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extend</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getExtend()
 * @model
 * @generated
 */
public interface Extend extends BodyElement
{
} // Extend
