/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extend</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link yaml.helper.dsl.yamlGenDsl.Extend#getParentSubfieldName <em>Parent Subfield Name</em>}</li>
 *   <li>{@link yaml.helper.dsl.yamlGenDsl.Extend#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getExtend()
 * @model
 * @generated
 */
public interface Extend extends BodyElement
{
  /**
   * Returns the value of the '<em><b>Parent Subfield Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent Subfield Name</em>' attribute.
   * @see #setParentSubfieldName(String)
   * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getExtend_ParentSubfieldName()
   * @model
   * @generated
   */
  String getParentSubfieldName();

  /**
   * Sets the value of the '{@link yaml.helper.dsl.yamlGenDsl.Extend#getParentSubfieldName <em>Parent Subfield Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent Subfield Name</em>' attribute.
   * @see #getParentSubfieldName()
   * @generated
   */
  void setParentSubfieldName(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Body)
   * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getExtend_Body()
   * @model containment="true"
   * @generated
   */
  Body getBody();

  /**
   * Sets the value of the '{@link yaml.helper.dsl.yamlGenDsl.Extend#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Body value);

} // Extend
