/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link yaml.helper.dsl.yamlGenDsl.Hint#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getHint()
 * @model
 * @generated
 */
public interface Hint extends Property
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getHint_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link yaml.helper.dsl.yamlGenDsl.Hint#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Hint
