/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends BodyElement
{
} // Property
