/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Source Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getSourceElement()
 * @model
 * @generated
 */
public interface SourceElement extends EObject
{
} // SourceElement
