/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Values</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link yaml.helper.dsl.yamlGenDsl.Values#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getValues()
 * @model
 * @generated
 */
public interface Values extends EObject
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslPackage#getValues_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // Values
