/**
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl.yamlGenDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see yaml.helper.dsl.yamlGenDsl.YamlGenDslFactory
 * @model kind="package"
 * @generated
 */
public interface YamlGenDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "yamlGenDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.helper.yaml/dsl/YamlGenDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "yamlGenDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  YamlGenDslPackage eINSTANCE = yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl.init();

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.SourceImpl <em>Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.SourceImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getSource()
   * @generated
   */
  int SOURCE = 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__ENTRIES = 0;

  /**
   * The number of structural features of the '<em>Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.SourceElementImpl <em>Source Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.SourceElementImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getSourceElement()
   * @generated
   */
  int SOURCE_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Source Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.ImportImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__PATH = SOURCE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = SOURCE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.FieldImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getField()
   * @generated
   */
  int FIELD = 3;

  /**
   * The feature id for the '<em><b>Help</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__HELP = SOURCE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Root</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__ROOT = SOURCE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = SOURCE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Super Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__SUPER_FIELD = SOURCE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__BODY = SOURCE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = SOURCE_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.BodyElementImpl <em>Body Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.BodyElementImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getBodyElement()
   * @generated
   */
  int BODY_ELEMENT = 5;

  /**
   * The number of structural features of the '<em>Body Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.ExtendImpl <em>Extend</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.ExtendImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getExtend()
   * @generated
   */
  int EXTEND = 6;

  /**
   * The number of structural features of the '<em>Extend</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTEND_FEATURE_COUNT = BODY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.BodyImpl <em>Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.BodyImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getBody()
   * @generated
   */
  int BODY = 4;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY__ELEMENTS = EXTEND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_FEATURE_COUNT = EXTEND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.NestedFieldImpl <em>Nested Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.NestedFieldImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getNestedField()
   * @generated
   */
  int NESTED_FIELD = 7;

  /**
   * The feature id for the '<em><b>Help</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELD__HELP = BODY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELD__MANDATORY = BODY_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELD__FIELD = BODY_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELD__BODY = BODY_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Nested Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELD_FEATURE_COUNT = BODY_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.NestedFieldsImpl <em>Nested Fields</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.NestedFieldsImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getNestedFields()
   * @generated
   */
  int NESTED_FIELDS = 8;

  /**
   * The feature id for the '<em><b>Help</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELDS__HELP = BODY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELDS__MANDATORY = BODY_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELDS__FIELD = BODY_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELDS__BODY = BODY_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Nested Fields</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NESTED_FIELDS_FEATURE_COUNT = BODY_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.PropertyImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 9;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = BODY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.NameImpl <em>Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.NameImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getName_()
   * @generated
   */
  int NAME = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME__VALUE = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.DefaultImpl <em>Default</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.DefaultImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getDefault()
   * @generated
   */
  int DEFAULT = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT__VALUE = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Default</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.HintImpl <em>Hint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.HintImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getHint()
   * @generated
   */
  int HINT = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HINT__VALUE = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Hint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HINT_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.PermittedValuesImpl <em>Permitted Values</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.PermittedValuesImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getPermittedValues()
   * @generated
   */
  int PERMITTED_VALUES = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMITTED_VALUES__VALUE = PROPERTY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Permitted Values</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMITTED_VALUES_FEATURE_COUNT = PROPERTY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link yaml.helper.dsl.yamlGenDsl.impl.ValuesImpl <em>Values</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see yaml.helper.dsl.yamlGenDsl.impl.ValuesImpl
   * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getValues()
   * @generated
   */
  int VALUES = 14;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES__VALUES = 0;

  /**
   * The number of structural features of the '<em>Values</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUES_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Source <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Source
   * @generated
   */
  EClass getSource();

  /**
   * Returns the meta object for the containment reference list '{@link yaml.helper.dsl.yamlGenDsl.Source#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Source#getEntries()
   * @see #getSource()
   * @generated
   */
  EReference getSource_Entries();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.SourceElement <em>Source Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source Element</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.SourceElement
   * @generated
   */
  EClass getSourceElement();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link yaml.helper.dsl.yamlGenDsl.Import#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Import#getPath()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Path();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute list '{@link yaml.helper.dsl.yamlGenDsl.Field#getHelp <em>Help</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Help</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Field#getHelp()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Help();

  /**
   * Returns the meta object for the attribute '{@link yaml.helper.dsl.yamlGenDsl.Field#isRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Root</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Field#isRoot()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Root();

  /**
   * Returns the meta object for the attribute '{@link yaml.helper.dsl.yamlGenDsl.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the reference '{@link yaml.helper.dsl.yamlGenDsl.Field#getSuperField <em>Super Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Field</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Field#getSuperField()
   * @see #getField()
   * @generated
   */
  EReference getField_SuperField();

  /**
   * Returns the meta object for the containment reference '{@link yaml.helper.dsl.yamlGenDsl.Field#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Field#getBody()
   * @see #getField()
   * @generated
   */
  EReference getField_Body();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Body <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Body
   * @generated
   */
  EClass getBody();

  /**
   * Returns the meta object for the containment reference list '{@link yaml.helper.dsl.yamlGenDsl.Body#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Body#getElements()
   * @see #getBody()
   * @generated
   */
  EReference getBody_Elements();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.BodyElement <em>Body Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body Element</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.BodyElement
   * @generated
   */
  EClass getBodyElement();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Extend <em>Extend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extend</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Extend
   * @generated
   */
  EClass getExtend();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.NestedField <em>Nested Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nested Field</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedField
   * @generated
   */
  EClass getNestedField();

  /**
   * Returns the meta object for the attribute list '{@link yaml.helper.dsl.yamlGenDsl.NestedField#getHelp <em>Help</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Help</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedField#getHelp()
   * @see #getNestedField()
   * @generated
   */
  EAttribute getNestedField_Help();

  /**
   * Returns the meta object for the attribute '{@link yaml.helper.dsl.yamlGenDsl.NestedField#isMandatory <em>Mandatory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mandatory</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedField#isMandatory()
   * @see #getNestedField()
   * @generated
   */
  EAttribute getNestedField_Mandatory();

  /**
   * Returns the meta object for the reference '{@link yaml.helper.dsl.yamlGenDsl.NestedField#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Field</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedField#getField()
   * @see #getNestedField()
   * @generated
   */
  EReference getNestedField_Field();

  /**
   * Returns the meta object for the containment reference '{@link yaml.helper.dsl.yamlGenDsl.NestedField#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedField#getBody()
   * @see #getNestedField()
   * @generated
   */
  EReference getNestedField_Body();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.NestedFields <em>Nested Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nested Fields</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedFields
   * @generated
   */
  EClass getNestedFields();

  /**
   * Returns the meta object for the attribute list '{@link yaml.helper.dsl.yamlGenDsl.NestedFields#getHelp <em>Help</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Help</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedFields#getHelp()
   * @see #getNestedFields()
   * @generated
   */
  EAttribute getNestedFields_Help();

  /**
   * Returns the meta object for the attribute '{@link yaml.helper.dsl.yamlGenDsl.NestedFields#isMandatory <em>Mandatory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mandatory</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedFields#isMandatory()
   * @see #getNestedFields()
   * @generated
   */
  EAttribute getNestedFields_Mandatory();

  /**
   * Returns the meta object for the reference '{@link yaml.helper.dsl.yamlGenDsl.NestedFields#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Field</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedFields#getField()
   * @see #getNestedFields()
   * @generated
   */
  EReference getNestedFields_Field();

  /**
   * Returns the meta object for the containment reference '{@link yaml.helper.dsl.yamlGenDsl.NestedFields#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.NestedFields#getBody()
   * @see #getNestedFields()
   * @generated
   */
  EReference getNestedFields_Body();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Name <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Name</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Name
   * @generated
   */
  EClass getName_();

  /**
   * Returns the meta object for the attribute '{@link yaml.helper.dsl.yamlGenDsl.Name#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Name#getValue()
   * @see #getName_()
   * @generated
   */
  EAttribute getName_Value();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Default <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Default</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Default
   * @generated
   */
  EClass getDefault();

  /**
   * Returns the meta object for the containment reference '{@link yaml.helper.dsl.yamlGenDsl.Default#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Default#getValue()
   * @see #getDefault()
   * @generated
   */
  EReference getDefault_Value();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Hint <em>Hint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hint</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Hint
   * @generated
   */
  EClass getHint();

  /**
   * Returns the meta object for the attribute '{@link yaml.helper.dsl.yamlGenDsl.Hint#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Hint#getValue()
   * @see #getHint()
   * @generated
   */
  EAttribute getHint_Value();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.PermittedValues <em>Permitted Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Permitted Values</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.PermittedValues
   * @generated
   */
  EClass getPermittedValues();

  /**
   * Returns the meta object for the containment reference '{@link yaml.helper.dsl.yamlGenDsl.PermittedValues#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.PermittedValues#getValue()
   * @see #getPermittedValues()
   * @generated
   */
  EReference getPermittedValues_Value();

  /**
   * Returns the meta object for class '{@link yaml.helper.dsl.yamlGenDsl.Values <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Values</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Values
   * @generated
   */
  EClass getValues();

  /**
   * Returns the meta object for the attribute list '{@link yaml.helper.dsl.yamlGenDsl.Values#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see yaml.helper.dsl.yamlGenDsl.Values#getValues()
   * @see #getValues()
   * @generated
   */
  EAttribute getValues_Values();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  YamlGenDslFactory getYamlGenDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.SourceImpl <em>Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.SourceImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getSource()
     * @generated
     */
    EClass SOURCE = eINSTANCE.getSource();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOURCE__ENTRIES = eINSTANCE.getSource_Entries();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.SourceElementImpl <em>Source Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.SourceElementImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getSourceElement()
     * @generated
     */
    EClass SOURCE_ELEMENT = eINSTANCE.getSourceElement();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.ImportImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__PATH = eINSTANCE.getImport_Path();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.FieldImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Help</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__HELP = eINSTANCE.getField_Help();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__ROOT = eINSTANCE.getField_Root();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Super Field</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__SUPER_FIELD = eINSTANCE.getField_SuperField();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__BODY = eINSTANCE.getField_Body();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.BodyImpl <em>Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.BodyImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getBody()
     * @generated
     */
    EClass BODY = eINSTANCE.getBody();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY__ELEMENTS = eINSTANCE.getBody_Elements();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.BodyElementImpl <em>Body Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.BodyElementImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getBodyElement()
     * @generated
     */
    EClass BODY_ELEMENT = eINSTANCE.getBodyElement();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.ExtendImpl <em>Extend</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.ExtendImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getExtend()
     * @generated
     */
    EClass EXTEND = eINSTANCE.getExtend();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.NestedFieldImpl <em>Nested Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.NestedFieldImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getNestedField()
     * @generated
     */
    EClass NESTED_FIELD = eINSTANCE.getNestedField();

    /**
     * The meta object literal for the '<em><b>Help</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_FIELD__HELP = eINSTANCE.getNestedField_Help();

    /**
     * The meta object literal for the '<em><b>Mandatory</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_FIELD__MANDATORY = eINSTANCE.getNestedField_Mandatory();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NESTED_FIELD__FIELD = eINSTANCE.getNestedField_Field();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NESTED_FIELD__BODY = eINSTANCE.getNestedField_Body();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.NestedFieldsImpl <em>Nested Fields</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.NestedFieldsImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getNestedFields()
     * @generated
     */
    EClass NESTED_FIELDS = eINSTANCE.getNestedFields();

    /**
     * The meta object literal for the '<em><b>Help</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_FIELDS__HELP = eINSTANCE.getNestedFields_Help();

    /**
     * The meta object literal for the '<em><b>Mandatory</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NESTED_FIELDS__MANDATORY = eINSTANCE.getNestedFields_Mandatory();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NESTED_FIELDS__FIELD = eINSTANCE.getNestedFields_Field();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NESTED_FIELDS__BODY = eINSTANCE.getNestedFields_Body();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.PropertyImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.NameImpl <em>Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.NameImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getName_()
     * @generated
     */
    EClass NAME = eINSTANCE.getName_();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAME__VALUE = eINSTANCE.getName_Value();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.DefaultImpl <em>Default</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.DefaultImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getDefault()
     * @generated
     */
    EClass DEFAULT = eINSTANCE.getDefault();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFAULT__VALUE = eINSTANCE.getDefault_Value();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.HintImpl <em>Hint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.HintImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getHint()
     * @generated
     */
    EClass HINT = eINSTANCE.getHint();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HINT__VALUE = eINSTANCE.getHint_Value();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.PermittedValuesImpl <em>Permitted Values</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.PermittedValuesImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getPermittedValues()
     * @generated
     */
    EClass PERMITTED_VALUES = eINSTANCE.getPermittedValues();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERMITTED_VALUES__VALUE = eINSTANCE.getPermittedValues_Value();

    /**
     * The meta object literal for the '{@link yaml.helper.dsl.yamlGenDsl.impl.ValuesImpl <em>Values</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see yaml.helper.dsl.yamlGenDsl.impl.ValuesImpl
     * @see yaml.helper.dsl.yamlGenDsl.impl.YamlGenDslPackageImpl#getValues()
     * @generated
     */
    EClass VALUES = eINSTANCE.getValues();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUES__VALUES = eINSTANCE.getValues_Values();

  }

} //YamlGenDslPackage
