/*
 * generated by Xtext 2.22.0
 */
package yaml.helper.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class YamlGenDslStandaloneSetup extends YamlGenDslStandaloneSetupGenerated {

	public static void doSetup() {
		new YamlGenDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
